sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NZpJGNXKgmgEurrn1pVHRq+peHz0jkiI/9ryqUxSAJVkT2IEc/XuXTf6QW4PfiZgXBfU/hLQabgMd9Mj46q4mgByQcgXyZ9r7tb6cmQn3ak7mZmXTXNtOcrEjmZavjNwM+chF5gjWMQ826t/rBxJ0UkjnF2kQ8rLlzj8tBDuZRXo9v+/L6HDfVYxczMgV7cygPET0z4KpqjV0Ojdartqd936FmauU5hZceHeKNnOOKUJG/HQkGlgt3+b3FB6+uZWNX/kpaJYiF9GHf5jaqIJcmax7JJEu78xur+jDkxYYQOFzdzeigLx1zte4xau5nUQl+1KqR4HzOf0FN0/HAfC1REgjpK/MYrszQxBm4KqvR9jcy08K5ny+lGFcYOJrJTRHK+ihCLBd0Mn57oOwDmRkfVTm1NtizzUWbfTSmM22vhUpDuSOAq4byKIaKKPngCQaIBl7PhbkgaT0bwXUktsTR5JcBjvcYGR0TGpxJtVwekUMM57o9K4hHgr5c+42U4UL1kRVOcI3SUu+XfAOT3n/JfdIAKy/5CeJqMzkr26Iaz7ZJhqN5XUK7f6L3rfQ96GEeo9e/JxCdEyJYp2Ve5rX9ayJB8BgMP6eZO/YYg5vaKjx+kD7/O7tjNcX/8Jmg+M0vHtn4F3X76ORx8JyGYzyoP7P8OXeQPyyeKaVCMVK8o=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Diary-of-Samuel-Pepys---Volume-32--December-1664_4152
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy